# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StvProject2.3.5' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StvProject2.3.5
 pod 'FMDB'
 pod 'sqlite3'

end
