# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StvProject2.5.8' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StvProject2.5.8
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

end
